name: User Story
description: Créer une user story
body:
  - type: input
    id: persona
    attributes:
      label: En tant que...
      placeholder: Identification du type d'utilisateur / Nom du persona

  - type: input
    id: besoin
    attributes:
      label: Je souhaiterais...
      placeholder: Description du besoin

  - type: textarea
    id: detail
    attributes:
      label: Détail du besoin
      placeholder: Informations complémentaires
